name: asif
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Dockeraction
      id: out
      uses: ./
    - name: step2
      run: echo " completed successfully and got ${{steps.out.outputs.output1}}"
